export const CUBE = {
  INITIAL_ROT_X: -18,
  INITIAL_ROT_Y: 28,
  DRAG_SENSITIVITY: 0.55,
  VELOCITY_FACTOR: 0.6,
  DAMPING: 0.92,
  LERP_FACTOR: 0.08,
  X_RETURN_FACTOR: 0.02,
  AUTO_SPEED: 0.3,
  VELOCITY_THRESHOLD: 0.05,
  IDLE_TIMEOUT_MS: 3000,
  MOUSE_Y_RANGE: 180,
  MOUSE_X_RANGE: 90,
};

export const CURSOR = {
  RING_LERP: 0.18,
};

export const EMAIL = {
  SERVICE_ID: import.meta.env.VITE_EMAILJS_SERVICE_ID,
  TEMPLATE_ID: import.meta.env.VITE_EMAILJS_TEMPLATE_ID,
  PUBLIC_KEY: import.meta.env.VITE_EMAILJS_PUBLIC_KEY,
};
